apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "server-chart.fullname" . }}
  labels: {{- include "server-chart.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.deployment.replicaCount }}
  selector:
    matchLabels:
      {{- include "server-chart.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "server-chart.labels" . | nindent 8 }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.deployment.container.image.repository }}:{{ .Values.deployment.container.image.tag }}"
          imagePullPolicy: {{ .Values.deployment.container.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.deployment.container.port }}
              name: {{ .Values.deployment.container.portName }}
          resources:
            requests:
              cpu: {{ .Values.deployment.container.resources.requests.cpu }}
              memory: {{ .Values.deployment.container.resources.requests.memory }}
            limits:
              cpu: {{ .Values.deployment.container.resources.limits.cpu }}
              memory: {{ .Values.deployment.container.resources.limits.memory }}
